//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: sandto1.proto
namespace sandto1
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FrSolar")]
  public partial class FrSolar : global::ProtoBuf.IExtensible
  {
    public FrSolar() {}
    
    private int _tempHaut;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"tempHaut", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tempHaut
    {
      get { return _tempHaut; }
      set { _tempHaut = value; }
    }
    private int _tempMilieu;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"tempMilieu", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tempMilieu
    {
      get { return _tempMilieu; }
      set { _tempMilieu = value; }
    }
    private int _tempBas;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"tempBas", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tempBas
    {
      get { return _tempBas; }
      set { _tempBas = value; }
    }
    private int _tempExt;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"tempExt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tempExt
    {
      get { return _tempExt; }
      set { _tempExt = value; }
    }
    private NodeMeta _metadata;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"metadata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public NodeMeta metadata
    {
      get { return _metadata; }
      set { _metadata = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FrEmontx")]
  public partial class FrEmontx : global::ProtoBuf.IExtensible
  {
    public FrEmontx() {}
    
    private uint _p1;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"p1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint p1
    {
      get { return _p1; }
      set { _p1 = value; }
    }
    private uint _p2;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"p2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint p2
    {
      get { return _p2; }
      set { _p2 = value; }
    }
    private uint _p3;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"p3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint p3
    {
      get { return _p3; }
      set { _p3 = value; }
    }
    private uint _p4;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"p4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint p4
    {
      get { return _p4; }
      set { _p4 = value; }
    }
    private uint _V;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"V", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint V
    {
      get { return _V; }
      set { _V = value; }
    }
    private int _T1;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"T1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int T1
    {
      get { return _T1; }
      set { _T1 = value; }
    }
    private int _T2;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"T2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int T2
    {
      get { return _T2; }
      set { _T2 = value; }
    }
    private NodeMeta _metadata;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"metadata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public NodeMeta metadata
    {
      get { return _metadata; }
      set { _metadata = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FrHygTh")]
  public partial class FrHygTh : global::ProtoBuf.IExtensible
  {
    public FrHygTh() {}
    
    private int _temp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"temp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int temp
    {
      get { return _temp; }
      set { _temp = value; }
    }
    private int _hygro;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"hygro", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hygro
    {
      get { return _hygro; }
      set { _hygro = value; }
    }
    private int _V;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"V", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int V
    {
      get { return _V; }
      set { _V = value; }
    }
    private NodeMeta _metadata;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"metadata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public NodeMeta metadata
    {
      get { return _metadata; }
      set { _metadata = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FrGlcd")]
  public partial class FrGlcd : global::ProtoBuf.IExtensible
  {
    public FrGlcd() {}
    
    private int _temp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"temp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int temp
    {
      get { return _temp; }
      set { _temp = value; }
    }
    private int _action;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int action
    {
      get { return _action; }
      set { _action = value; }
    }
    private NodeMeta _metadata;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"metadata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public NodeMeta metadata
    {
      get { return _metadata; }
      set { _metadata = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FrCommand")]
  public partial class FrCommand : global::ProtoBuf.IExtensible
  {
    public FrCommand() {}
    
    private int _cmd;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private int _v1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"v1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int v1
    {
      get { return _v1; }
      set { _v1 = value; }
    }
    private int _v2;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"v2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int v2
    {
      get { return _v2; }
      set { _v2 = value; }
    }
    private NodeMeta _metadata;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"metadata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public NodeMeta metadata
    {
      get { return _metadata; }
      set { _metadata = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FrSetTime")]
  public partial class FrSetTime : global::ProtoBuf.IExtensible
  {
    public FrSetTime() {}
    
    private uint _year;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"year", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint year
    {
      get { return _year; }
      set { _year = value; }
    }
    private uint _month;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"month", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint month
    {
      get { return _month; }
      set { _month = value; }
    }
    private uint _day;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"day", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint day
    {
      get { return _day; }
      set { _day = value; }
    }
    private uint _hour;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"hour", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint hour
    {
      get { return _hour; }
      set { _hour = value; }
    }
    private uint _minute;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"minute", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint minute
    {
      get { return _minute; }
      set { _minute = value; }
    }
    private uint _second;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"second", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint second
    {
      get { return _second; }
      set { _second = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FrGatewayStatus")]
  public partial class FrGatewayStatus : global::ProtoBuf.IExtensible
  {
    public FrGatewayStatus() {}
    
    private uint _ram;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ram", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ram
    {
      get { return _ram; }
      set { _ram = value; }
    }
    private uint _millis;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"millis", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint millis
    {
      get { return _millis; }
      set { _millis = value; }
    }
    private uint _nodeid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"nodeid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint nodeid
    {
      get { return _nodeid; }
      set { _nodeid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NodeMeta")]
  public partial class NodeMeta : global::ProtoBuf.IExtensible
  {
    public NodeMeta() {}
    
    private uint _nodeFrom;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nodeFrom", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint nodeFrom
    {
      get { return _nodeFrom; }
      set { _nodeFrom = value; }
    }
    private uint _nodeTo = (uint)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"nodeTo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint nodeTo
    {
      get { return _nodeTo; }
      set { _nodeTo = value; }
    }
    private int _rx_rssi = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"rx_rssi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int rx_rssi
    {
      get { return _rx_rssi; }
      set { _rx_rssi = value; }
    }
    private uint _Vbatt = (uint)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Vbatt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint Vbatt
    {
      get { return _Vbatt; }
      set { _Vbatt = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SanDto1")]
  public partial class SanDto1 : global::ProtoBuf.IExtensible
  {
    public SanDto1() {}
    
    private SanDto1.FrameType _frameType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"frameType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public SanDto1.FrameType frameType
    {
      get { return _frameType; }
      set { _frameType = value; }
    }
    private int _nodeFrom;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nodeFrom", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nodeFrom
    {
      get { return _nodeFrom; }
      set { _nodeFrom = value; }
    }
    private int _nodeTo = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"nodeTo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int nodeTo
    {
      get { return _nodeTo; }
      set { _nodeTo = value; }
    }
    private int _rx_rssi = (int)-1;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"rx_rssi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)-1)]
    public int rx_rssi
    {
      get { return _rx_rssi; }
      set { _rx_rssi = value; }
    }
    private FrEmontx _emontxfr = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"emontxfr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FrEmontx emontxfr
    {
      get { return _emontxfr; }
      set { _emontxfr = value; }
    }
    private FrSolar _pushsolar = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"pushsolar", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FrSolar pushsolar
    {
      get { return _pushsolar; }
      set { _pushsolar = value; }
    }
    private FrGlcd _eglcdfr = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"eglcdfr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FrGlcd eglcdfr
    {
      get { return _eglcdfr; }
      set { _eglcdfr = value; }
    }
    private FrHygTh _hygthfr = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"hygthfr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FrHygTh hygthfr
    {
      get { return _hygthfr; }
      set { _hygthfr = value; }
    }
    private FrCommand _commandfr = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"commandfr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FrCommand commandfr
    {
      get { return _commandfr; }
      set { _commandfr = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"FrameType")]
    public enum FrameType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FR_emontx", Value=1)]
      FR_emontx = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FR_glcd", Value=2)]
      FR_glcd = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FR_hygth", Value=3)]
      FR_hygth = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FR_commands", Value=4)]
      FR_commands = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FR_solar", Value=5)]
      FR_solar = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FR_test", Value=6)]
      FR_test = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FR_lifeframe", Value=7)]
      FR_lifeframe = 7
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}